### ISSUE TITLE
Different output if either jspm or systemjs-builder is used

### ISSUE THREAD

**Issue by Munter** [Munter/express-systemjs-translate#165]
I'm trying to implement a test to verify that the output is correct when bundling (default behavior).

The output of a bundle with dependencies differs based on if I use the jspm provided builder or systemjs-builder to create the bundle.

Consider this source code:
```js
var foo = require('./stringExport.js');

module.exports = {
  foo: foo
};
```

Output with jspm:

```js
System.registerDynamic("lib/stringExport.js", [], true, function($__require, exports, module) {
  ;
  var define,
      global = this,
      GLOBAL = this;
  module.exports = 'foo';
  return module.exports;
});

System.registerDynamic("lib/requireWorking.js", ["lib/stringExport.js"], true, function($__require, exports, module) {
  ;
  var define,
      global = this,
      GLOBAL = this;
  var foo = $__require('lib/stringExport.js');
  module.exports = {foo: foo};
  return module.exports;
});
```

Output with systemjs-builder:
```js
System.registerDynamic("lib/stringExport.js", [], true, function($__require, exports, module) {
  ;
  var define,
      global = this,
      GLOBAL = this;
  module.exports = 'foo';
  return module.exports;
});

System.registerDynamic("lib/requireWorking.js", ["./stringExport.js"], true, function($__require, exports, module) {
  ;
  var define,
      global = this,
      GLOBAL = this;
  var foo = $__require('./stringExport.js');
  module.exports = {foo: foo};
  return module.exports;
});
```

Notice the difference in how the dependency is described. Jspm resolves the `'./stringExport'` dependency to `'lib/stringExport.js'` while systemjs-builder keeps it as is.

This behavior is unaffected by using SystemJS configured with `defaultJsExtensions` enabled or disabled.

Is this a bug or the desired behavior?

ping @guybedford @gustavnikolaj @papandreou

**Comment by Munter** [comment]
This is an example of a failed test: https://travis-ci.org/Munter/express-systemjs-translate/jobs/143703685#L300

The 'test-bundle-switch' branch has a working setup to reproduce this error

**Comment by papandreou** [comment]
Is it still different if you pass `normalize: true` as an option when building with systemjs-builder?

**Comment by Munter** [comment]
setting `normalize: true` in the build options does align the behaviours across the two setups. Should I make this a default in the middleware?

**Comment by papandreou** [comment]
I ended up always passing `normalize:true` in `bundleSystemJs` in assetgraph (https://github.com/assetgraph/assetgraph/blob/master/lib/transforms/bundleSystemJs.js#L596-L605) in order to get the `inlineSingularConditions` option working, which was a prereq for getting certain builds utilizing conditional substitution to work with the condition value specified up front. From what Guy said it seemed safe, but I can't tell what the exact implications are in this particular scenario.

**Comment by gustavnikolaj** [comment]
I just verified that our feature branch still works after adding `normalize: true` to the build flags. It changes the names of the dependencies in the bundled code, but other than that it still works the same.

**Comment by alexisvincent** [comment]
normalize: true breaks my build, with the following error Unable to build dependency github:jspm/nodelibs-process@0.2.0-alpha/#:./process.js. normalize must be disabled for bundles containing conditionals

**Comment by Munter** [comment]
I'd like to add a test case to the unit tests with the package that causes this. Just to be sure we don't regress into this again when I flip the default to be `normalize: false`.

Which jspm package did this dependency chain originate in?
