### ISSUE TITLE
Integration with browserSync

### ISSUE THREAD

**Issue by lookfirst** [Munter/express-systemjs-translate#167]
This is awesome, but I'm heavily dependent on BrowserSync. I tried adding this as a middleware to BS, but got an error:

`
TypeError: req.get is not a function
  at /node_modules/express-systemjs-translate/lib/index.js:152:22
`

Thoughts?

**Comment by Munter** [comment]
`req.get()` is an express 4 method. skimming over the BrowserSync code it looks like it's using connect instead of express. I'll see if I can recreate the problem with connect in the tests as well

**Comment by Munter** [comment]
Connect tests seem to run fine. So `req.get()` seems to be compatible with connect. So either that's not the problem or it's an outdated version in your install of browsersync

**Comment by Munter** [comment]
I've attempted a fix, but I'm working blind because I have no browsersync setup to run this in. Could I ask you to `npm install Munter/express-systemjs-translate#fix-issue-167` instead of the npm release and tell me if the problem is fixed?

**Comment by Munter** [comment]
Scratch that. I think I have solved it now. Release coming up as soon as CI tests pass

**Comment by Munter** [comment]
Published in v3.0.1

Thanks for the report!

**Comment by lookfirst** [comment]
👍   this seems to be working now. next up trying to figure out what the other error i'm getting is... will file another issue if i can't figure it out...
