### ISSUE TITLE
Unable to build dependency

### ISSUE THREAD

**Issue by lookfirst** [Munter/express-systemjs-translate#171]
I see this in my console:

`Unable to build dependency github:jspm/nodelibs-process@0.2.0-alpha/#:./process.js. normalize must be disabled for bundles containing conditionals.`

No idea how to fix it. I'm not using process anywhere.

**Comment by lookfirst** [comment]
```
			translate({
				baseUrl: path.war,
				configFile: 'jspm.config.js'
			})
```

**Comment by Munter** [comment]
I added `normalize: true` to the systemjs-builder's build options by default because I wasn't aware of any way this could break. Can you try this config?

```js
translate({
  serverRoot: path.war,
  baseUrl: path.war,
  configFile: 'jspm.config.js',
  buildFlags: {
    normalize: false
  }
});
```

**Comment by lookfirst** [comment]
Ok, that worked! =)

**Comment by Munter** [comment]
@papandreou I'll have to change the default here again. Might be relevant for assetgraph-builder as well. I'll just add the setting explicitly in my tests in order to force identical output

**Comment by papandreou** [comment]
Hmm, that's weird. The ability to substitute conditionals were the reason why I had to *add* normalize:true.

@lookfirst, are you able to share your app, or maybe just a small part that causes this to happen?

**Comment by lookfirst** [comment]
@papandreou Sorry, large private app. No idea why that happens. =(

**Comment by Munter** [comment]
Could you tell us what the top level package is that has this nested dependency? We should be able to recreate the problem just by installing that package and importing its main

**Comment by lookfirst** [comment]
How do I figure that out?

**Comment by Munter** [comment]
v4.0.0 is out. serverRoot is now required and normalization is false by default: https://github.com/Munter/express-systemjs-translate/releases/tag/v4.0.0
