### ISSUE TITLE
v3.2.0, 3.1.0: Unable to calculate canonical name to bundle 

### ISSUE THREAD

**Issue by arcticShadow** [Munter/express-systemjs-translate#175]
Tried latest version to see if extra logging showed anything interesting. Found the following error for each bundle attempted to retreive. 
```bash
Error: express-systemjs-translate: Unable to calculate canonical name to bundle file:///Users/coledi/Projects/node/emrc-webapp/jspm_packages/npm/jquery@2.2.4.js. Ensure that this module sits within the baseURL or a wildcard path config.
```

Same thing happens on v3.2.0 and 3.1.0, but works fine on v3.0.1

**Comment by Munter** [comment]
I did change some things in the path resolving behavior in order to get the correct `sourceRoot` in the source map. That might have introduced this error.

Does that path actually exist on your file system? 
What paths do your `serverRoot` and `baseUrl` options set?

**Comment by arcticShadow** [comment]
Yep that path is correct. (although as for the file:// scheme, thats not part of my config)

Heres a partial snippet of my `config.js`, exclusing the humongous map section. as far as i know, i'm not setting serverRoot

```javascript
System.config({
  baseURL: "/emrc/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  meta: {
    "*.css": {
      "loader": "css"
    },
    "npm:moment@2.8.3": {
      "format": "cjs"
    }
  },
```

**Comment by Munter** [comment]
Try setting `serverRoot` I think I should consider making it mandatory now with the updated path resolving. If I don't know the server root source maps can't map `baseURL --> file` paths to root relative paths.

I wonder how I can make that part of the configuration more approachable

**Comment by arcticShadow** [comment]
setting the `serverRoot` option in `translate` options makes things start working

**Comment by arcticShadow** [comment]
ahh you beat me to the punch.

Could you elaborate the `sourceRoot` from a property in the package.json?

**Comment by Munter** [comment]
ok. So I either need to figure out a way to make things work or log a warning when there is no `serverRoot` or make `serverRoot` mandatory. Which would be the most intuitive to you?

**Comment by Munter** [comment]
I doubt I can make it "just work" without

**Comment by arcticShadow** [comment]
Cool. I'd suggest updating your readme example for serverRoot to not include " // This setting is not in active use at the moment" :-D it's a bit misleading.

**Comment by Munter** [comment]
I'm not aware of any standard or convention that will let me extrapolate from package.json where the root of the development web server will be. I wish express middleware could tap into the express server itself here. Eventually there will be some sort of static handler at the end that will know the root

**Comment by Munter** [comment]
I'll update the docs and make `serverRoot` a required property for now, throwing an exception if it is not set. Major version, here we come

**Comment by Munter** [comment]
v4.0.0 is out. serverRoot is now required and normalization is false by default: https://github.com/Munter/express-systemjs-translate/releases/tag/v4.0.0
